FROM microsoft/dotnet-framework:4.7.2-sdk AS base

# if your company or enterprise is using ssl interception, this is where you need to install certs for the egress
# RUN Import-Certificate -FilePath <path> -CertStoreLocation <location>

FROM base as site
WORKDIR /src
COPY . .
RUN nuget restore ServiceMonitor.sln
WORKDIR /src/DemoWebsite
RUN msbuild DemoWebsite.csproj /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=c:\output

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2
COPY --from=site /output /inetpub/wwwroot